// Single source of truth: OpenAPI types generated by `npm run api:gen`.
//
// This file intentionally derives app-facing types from OpenAPI `paths` so that:
// - Before generation, everything is `any` (placeholder) but the app still compiles.
// - After generation, types become precise without manual duplication.

import type { paths } from "./gen/api-types";

type JsonContent<T> = T extends { content?: infer C }
  ? C extends { "application/json"?: infer J }
    ? J
    : C extends { "application/*+json"?: infer J }
      ? J
      : any
  : any;

type ResponseOf<Op, Code extends string> = Op extends { responses?: infer R }
  ? R extends Record<string, any>
    ? Code extends keyof R
      ? JsonContent<R[Code]>
      : any
    : any
  : any;

type RequestBodyOf<Op> = Op extends { requestBody?: infer RB }
  ? JsonContent<RB>
  : any;

type LoginOp = paths["/api/auth/login"]["post"];
type RegisterOp = paths["/api/auth/register"]["post"];
type ItemsGetOp = paths["/api/items"]["get"];
type DecideOp = paths["/api/decide"]["post"];
type DecisionsListOp = paths["/api/decisions"]["get"];
type DecisionGetOp = paths["/api/decisions/{id}"]["get"];
type PreferencesGetOp = paths["/api/preferences"]["get"];
type PreferenceProfilePutOp = paths["/api/preferences/profile"]["put"];
type DecisionFeedbackPostOp = paths["/api/decisions/{id}/feedback"]["post"];

export type AuthResponse = ResponseOf<LoginOp, "200">;
export type UserAccount = ResponseOf<RegisterOp, "201">;
export type Item =
  ResponseOf<ItemsGetOp, "200"> extends (infer T)[]
    ? T
    : ResponseOf<ItemsGetOp, "200">;
export type DecideResponse = ResponseOf<DecideOp, "200">;
export type Decision = ResponseOf<DecisionGetOp, "200">;
type InferredFeedbackStatus = Decision extends {
  feedback?: { status?: infer S } | null;
}
  ? S
  : never;
export type FeedbackStatus =
  | Extract<InferredFeedbackStatus, string>
  | "ACCEPT"
  | "REJECT"
  | "SKIP";
export type UserPreference = ResponseOf<PreferencesGetOp, "200">;
export type PreferenceProfileUpdate = RequestBodyOf<PreferenceProfilePutOp>;
export type FeedbackRequest = RequestBodyOf<DecisionFeedbackPostOp>;
type InferredFeedbackCategory = FeedbackRequest extends {
  category?: infer C | null;
}
  ? C
  : never;
export type FeedbackReasonCategory =
  | Extract<InferredFeedbackCategory, string>
  | "PRICE"
  | "TASTE"
  | "DIET"
  | "AVAILABILITY"
  | "VARIETY"
  | "OTHER";

// If you need list types, keep these helpers local and derived too.
export type DecisionList = ResponseOf<DecisionsListOp, "200">;

export type Tab = "auth" | "items" | "decide" | "decisions";
